socrata-platform/data-coordinator

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/MainTest.scala
We were only checking to make sure we have the right number of copies total, making secondary groups not
work at all.
I wrote this over a year ago with the exact use case I have now in mind, only we haven't used it yet
and I failed on writing tests because I could barely write Scala so it didn't work.  The test now is
weak, but I didn't want to refactor the whole class right now.
The only intended actual code change is adding "intersect(secondaryGroup.instances)", everything else is
just to get the logic in a place it can be easily tested.
> Fix secondary groups so we actually ensure we have the desired number of copies in each group.

- coordinator/docker/README.md
- coordinator/docker/data-coordinator.conf.j2
NOTE: Don't merge, just let me know if it looks good.  Need to coordinate
with marathon config changes.
Related: https://github.com/socrata/apps-marathon/pull/23
> Modify data coordinator to allow passing in the whole secondary config.

- coordinator/docker-secondary-watcher/secondary-watcher.conf.j2
- coordinator/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
Running out of pooled connections can result in strange and difficult to detect failure conditions. For example, the claim manager can get blocked resulting in claims not being updated and thus stolen. We control concurrency by the number of workers combined with the number of secondary instances configured, so we set it to a "essentially unlimited" value for the secondary watcher.
> effectively unlimited query pool for secondary watcher

- coordinator/src/main/resources/reference.conf
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Service.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/ServiceConfig.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/AbstractRepBasedDataSqlizer.scala
Each mutation thread can use a significant amount of memory due to batching up mutations before writing to truth.  Cap the number of mutation threads allowed using an AtomicInteger.  Note this number should be smaller than the total number of threads serving requests to allow for exports and other requests.  
Also, reduce the default batch size.
> Cap DC memory usage - limit # mutation threads

- coordinator/src/main/resources/reference.conf
- coordinator/src/main/scala/com/socrata/datacoordinator/common/SoQLCommon.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcherConfig.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/secondary/SecondaryWatcherTest.scala
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20150528-add-column-retry-num.xml
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20150601-add-column-initially-claimed-at.xml
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20150601-add-column-next-retry.xml
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/migrate.xml
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryManifest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
- coordinatorlib/src/test/scala/com/socrata/datacoordinator/truth/loader/sql/TestSqlLoader.scala
- coordinatorlib/src/test/scala/com/socrata/datacoordinator/truth/reader/sql/SqlReaderTest.scala
- project/Coordinator.scala
- project/CoordinatorLib.scala
- project/Dependencies.scala
This PR adds functionality to automatically retry on failure, with exponential back off.  More precisely, on failure, the dataset is marked broken only if the # of retries has not been exceeded; otherwise the retry information is updated in the secondary_manifest table, and the watcher can pick up the job again.
The back off interval and max number of retries can be configured in the secondary watcher .conf file.
Also, a test for the secondary watcher has been added.
> [CORE-5319] Auto retry on replication failure

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
* secondaries not in the default group will get datasets propagated from soda-fountain
> assembly sec instances from groups config

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
"interval '10 seconds'" is a special syntactic form, not a function
application, so "interval ?" does not work.  Instead, cast a string
value to an interval.
I noticed errors about this in the secondary watcher logs.
> Syntax error in updateRetryInfo

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/DatasetMap.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
By having it do a SELECT .. FOR SHARE on the dataset map row instead of
a SELECT .. FOR UPDATE.
> Make resync conflict with writes but not other resyncs

- project/Dependencies.scala
2016-03-03 03:04:30,477 ERROR [Worker 3 for secondary pg1-rc] () [] SecondaryWatcher Uncaught exception in thread Worker 3 for secondary pg1-rc, exiting
java.lang.NoSuchMethodError: com.socrata.soql.types.SoQLType$.typePreferences()Lscala/collection/Seq;
at com.socrata.soql.functions.SoQLTypeInfo$.<init>(SoQLTypeInfo.scala:14)
at com.socrata.soql.functions.SoQLTypeInfo$.<clinit>(SoQLTypeInfo.scala)
at com.socrata.pg.store.RollupManager$$anonfun$doUpdateRollup$1.apply$mcV$sp(RollupManager.scala:90)
at com.socrata.pg.store.RollupManager$$anonfun$doUpdateRollup$1.apply(RollupManager.scala:85)
at com.socrata.pg.store.RollupManager$$anonfun$doUpdateRollup$1.apply(RollupManager.scala:85)
> EN-3487 - align soql reference version with soql-postgres-adapter

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/SecondariesOfDatasetResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryManifest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
Enpoint now includes:
- version of dataset in truth
- map from secondary store ids to version
- feedback secondary stores
> EN-3886: Change /manifest/secondaries-of-dataset

- coordinator/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
This is dynamically generated in the docker world and is useful to help track which jobs
are claimed where.
> Include secondary watcher claim manager uuid in startup message.

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
Because the latest might be a discarded copy while the NEWEST might
be an earlier version that has been updated (e.g., if a working copy
is discarded and the remaining published copy is then updated).
> Update secondary-map to the NEWEST data version, not the LATEST

- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/triggers/update-dataset-log-trigger.xml
Use the _highest_ data version.  Because that's correct.
> Don't use the new row's data version when updating by trigger

- coordinator/docker-secondary-watcher/Dockerfile
Jenkins jobs are updated to build the code with Java 8. Build passed in Jenkins when I ran it on this branch.
This is part 1 of 2 of updating secondary watchers to run as Java8. Once this is merged, I'll cut a new release/docker image. The base image for PG and spandex secondary watchers can then be bumped to this new version. FYI: @sokrahta
> EN-5912: Use Java8 base image for dockerizing secondary-watcher

- coordinator/src/main/scala/com/socrata/datacoordinator/primary/SchemaMigrator.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/migration/Migration.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/migration/NonCommittingJdbcConnection.scala
Run migration in one transaction.
> Acquiring locks timeouts in 30s for migration.

- coordinator-external/src/main/scala/com/socrata/datacoordinator/external/DataCoordinatorError.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Exporter.scala
- project/Dependencies.scala
- project/SecondaryLibFeedback.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/DataCoordinatorClient.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackCookie.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/RequestFailure.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/instance/FeedbackSecondaryInstance.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/instance/SoQLValueRep.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/instance/config/FeedbackSecondaryInstanceConfig.scala
Export source column rows from core to compute values
for newly created computed columns:
* Changes retry limit config names
* Changes the name of cookie field
> EN-6889: Stop resyncing on computed column creation

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/DatasetMap.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
- version.sbt
PG secondary needs to use this when initially creating its dataset, so
that it can create the correct initial copy when it is not copy #1.
> Add `unsafeCreateDatasetAllocatingSystemId`

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
Change claim query to run on primary key (by using a subselect of original
filters), which will be locking at most one row instead of potentially
hundreds or thousands of rows. If this is the cause of -all- of the
deadlock issues (we see others on attempting to update claimedAt as
well), then yay. If not, then further fixes will be needed.
> EN-5687: hopefully fix secondary_manifest claim deadlocks

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/SecondariesOfDatasetResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20161006-add-column-group-name.xml
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/migrate.xml
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryStoresConfig.scala
Additions to `/secondaries-of-dataset` endpoint:
* `latest` data-version
* `published` data-version
* `unpublished` data-version
* `groups` - a map from `group_name` to the set of
`store_id`s (only the `store_id`s that the dataset
is replicated to)
Migration: Adds a column `group_name`
to the `secondary_stores_config` table.
> EN-5578: Expand `/secondaries-of-dataset` endpoint

- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20161014-add-secondary-manifest-queue-index.xml
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/migrate.xml
It isn't perfect because we don't quite express things in the right
way in secondary_manifest, but is much improved.  This normally
doesn't make a big difference, but is very very significant if you have
old transactions preventing vacuuming of secondary_manifest combined with a
lot of updates.
> EN-11190: Create index on secondary_manifest for efficient querying by secondary watcher.

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/DataCoordinatorClient.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
Use the `"no_such_row_to_update"` non-fatal error option
in mutation scripts.
> EN-11329: Fix 400s from DC for posting deleted rows

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
Add retry logic around releasing claims in secondary-watcher.
> EN-4308: Improve secondary-watcher claim releasing

- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/triggers/update-dataset-log-trigger.xml
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlDatasetDropper.scala
- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
When updating multiple rows on the`secondary_manifest`
in `truth` first obtain locks on the rows in a
deterministic order to avoid deadlocks.
For this: order by `dataset_system_id` then `store_id`.
> EN-12729: Avoid deadlocks on `secondary_manifest`

- bin/run_migrations.sh
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20170330-add-column-resource-name.xml
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/migrate.xml
We want to start storing dataset resource_name in truth
so the secondary-watcher can include the external dataset
ids in messages in AMQ reporting replication complete.
These replication messages are so we can wait to calculate
column stats after replication is complete.
Also, update migrations script to use sbt instead of first
assembling a new jar (because that is slow).
> EN-15144: Add column for dataset resource_name

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Mutator.scala
- coordinatorlib/src/main/protobuf/LogData.proto
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/DatasetInfo.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/DatabaseAccessors.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/messages/FromProtobuf.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/DatasetInfo.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/DatasetMap.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
Add "resource" as an optional field to the dataset
creation "c" command in creation mutation scripts.
Read and write optional/nullable `resource_name`
from `dataset_map`.
Dataset `resource_name` will be used in Eurybates
messages for replication completion events sent
from secondary-watcher for waiting to compute NBE
column statistics.
Depends upon migration in:
990536323ace1fcb22288f97f9d17cba81025eec
> EN-15144: Optionally write/read resource_name

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/DataSourceFromConfig.scala
- project/CoordinatorLib.scala
And strongly type them right into some classes.
A param we want to use cancelSignalTimeout requires 9.4.1209 or higher:
https://jdbc.postgresql.org/documentation/94/connect.html
> EN-1281: add support for more JDBC timeout configs

- project/BuildSettings.scala
This is a good thing to do anyway, but the specific reason for doing
it is it looks like different versions are fighting resulting in
strange "java.lang.ClassNotFoundException: scala.Some" errors.
I briefly looked at upgrading past 2.10, but we are still blocked by the
sbt-scalabuff plugin, which we would need to either fork and update or
replace.
> Explicitly pin Scala version.

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/DatabaseAccessors.scala
- project/Dependencies.scala
We want to do this now so that we will not be blocked if there is an urgent need to bump soil-ref for non join related work.
> EN-16084 Minimimal change to bump soql-ref version.

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/CookieOperatorTest.scala
Calculate deleted columns correctly in Feedback Secondary
to avoid looping infinitely and running out of memory.
Also add unit tests for deleteColumns function.
> EN-17248: delete columns correctly in Feedback S.

- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20170915-migrate-geocoding-secondary-cookie.xml
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/migrate.xml
Migrate geocoding secondary cookie to reflect changes to cookie
logic from commit 2183e78064db3b916af01e6a1321cb2064d0d3ec in
FeedbackSecondary library. This should be run _before_ using the
new version 0.0.17 of secondary-watcher-geocoding and should be
safe to run at anytime prior.
> EN-18249: Migrate geocoding secondary cookie

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
Hack secondaries-of-dataset endpoint to return the min
of the feedback secondary version and the actual version
of a store for all stores.
This is so the views/4x4/replication.json endpoint can return
false for read replication being up to date if feedback
replication is still behind. This is to avoid customers potentially
running into problems if they have scripts checking the read up to
date value as we migrate all existing region coded datasets to
use the geocoding-secondary.
> EN-18250: Hack secondaries-of-dataset endpoint

- version.sbt
Hack secondaries-of-dataset endpoint to return the min
of the feedback secondary version and the actual version
of a store for all stores.
This is so the views/4x4/replication.json endpoint can return
false for read replication being up to date if feedback
replication is still behind. This is to avoid customers potentially
running into problems if they have scripts checking the read up to
date value as we migrate all existing region coded datasets to
use the geocoding-secondary.
> EN-18250: Hack secondaries-of-dataset endpoint (#186)

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/PostgresRepBasedDataSqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlLoader.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/Sqlizer.scala
I think the problem with the last one is that I didn't take into
account the fact that batch size gets smaller (in terms of rows) as
datasets get wider.  So instead let's (a) keep track of _row counts_
instead of _batches_ and (b) decrease the frequency of ANALYZEs we
issue as datasets get larger, so that we only redo them if the row
count changes by a significant amount (25% of the total row count or
10000 rows, whichever is larger).
> Periodically update stats, take two.

- README.md
- coordinatorlib/src/it/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMapWriterTest.scala
- project/CoordinatorLib.scala
- project/Dependencies.scala
* Get the test compiling and passing again.
* Bring in scalatest so `sbt it:test` runs successfully.
This test will not run on CloudBees but we will try to get
jenkins-build to run it. Now Requires a test database
datacoordinator_test instead of blist_test (core's test db).
> EN-19395: Resurrect PostgresDatasetMapWriterTest 

- coordinatorlib/src/it/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMapWriterTest.scala
Get PostgresDatasetMapWriterTest running on Jenkins.
There seems to be a syntax error around encoding=UTF8
when the test is run on Jenkins.
> EN-19395: Get PostgresDatasetMapWriterTest running

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
Support handling computed columns with no source columns.
This is to support geocoded computed columns with only default values
and no source columns, since although they are silly there is no
reason for them to be invalid.
> EN-7442: Support computed columns with no sources

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Mutator.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Service.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/DatabaseAccessors.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/Loader.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/AbstractRepBasedDataSqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/PostgresRepBasedDataSqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlLoader.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/Sqlizer.scala
- coordinatorlib/src/test/scala/com/socrata/datacoordinator/truth/loader/sql/StupidSqlLoader.scala
- coordinatorlib/src/test/scala/com/socrata/datacoordinator/truth/loader/sql/TestSqlLoader.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/DataCoordinatorClient.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackCookie.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/RequestFailure.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/CookieOperatorTest.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/TestData.scala
Add by_system_id option to row_data command in the mutation script.
The option only changes the behavior of upserts and deletes for
datasets with user primary keys set in the following ways:
- updates may be made to rows using the system id column.
- if a user primary key column value and a system id colum
value is given, the user primary key is prefered.
- all deletes are assumed to be made using the system id column.
This option is to support the FeedbackSecondary library so that
a feedback secondary does not need to track the user primary key
column and not have to make guesses about if the primary key
column has changed based on errors from data-coordinator.
WIP: need to verify that the log_data has not been altered, and
fix the remaining failing unit test.
> EN-19241: Add by_system_id option to row_data cmd

- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20171020-migrate-geo-secondary-cookie-pk-to-sid.xml
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/migrate.xml
FeedbackSecondary no longer tracks primary key column of datasets,
but just uses the system id.
Migration to reflect changes in the cookie. This migration will
require down time for the geocoding-secondary (i.e. take the
secondary down, run the migration, then start the secondary on
the new version).
The rollback for the migration is not a perfect rollback since it
sets the primary key as the system id :id regardless if that is
true, but it is a good enough recoverable state and safer to run.
> EN-19241: FB secondary nolonger tracks primary key

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondaryTest.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/TestData.scala
Always export the system id column from data-coordinator
since if the dataset has a user primary key column set
data-coordinator will not return the system id column
by default. This is because now FeedbackSecondary
nows does everything by system id and not by primary key.
Fixes bug where system id column is not found in export
from data-coordinator when a user primary key is set
on the dataset. Introduced in commit:
2c58c73e4abb6bc50f0f91bd53da350be8f0f896
> EN-19241: Fix FeedbackSecondary library

- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
The immediate motivation for this is that when I'm running secondary
watcher locally and sleep my laptop for a while, when it comes back
the connection pool is closed for some reason and secondary watcher
spins in a tight loop trying to update claims.  Hopefully the root
cause of this will be easier to figure out without the tight spin
loop.
Spinning in this loop is also something we could see in production
if the truth database is unavailable, etc.
> Avoid tight spin loop if we have errors updating SW claims.

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/DataCoordinatorClient.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondaryTest.scala
Fix FeedbackSecondary library code to properly use an iterator
when exporting row data from data-coordinator to avoid OOMing
on large datasets.
> EN-20087: Stop FeedbackSecondary OOMing on export

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetSecondaryStatusResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/MainTest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/config/SecondaryConfig.scala
Support delete on /secondary-manifest for "full" stores or stores we
other wise have decided we do not want to send new datasets to.
Add configuration for specifying instances in a secondary group
that are not accepting new datasets. With this change, we will
not remove secondary instances in a group from data-coordinator's
config that are full, but instead add them to the set of instances
not accepting new datasets for the group in question.
This fixes delete not working on /secondary-manifest for full stores
that have been removed from data-coordinator's config by not removing
them from data-coordinator's config to start with.
This will also support data-coordinator's future collocation logic
to be able to know about all instances in a secondary group, but
still know about which stores …
> EN-5487: Support delete on S-M for "full" stores

- configs/sample-data-coordinator.conf
For sample local dev configuration use database name
`datacoordinator` and instance name `primus` to match
existing setup of local dev environments done by the
onramp script.
> SPARTA: For local dev use naming in onramp script

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/PostgresCollocationManifest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlCollocationManifest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/PostgresUniverse.scala
Fix insert into collocation manifest as part of executing
collocation. ON CONFLICT in INSERT statements is not supported
until PostgreSQL 9.5 but we are still running some truth
servers on PostgreSQL 9.4.
> EN-17025: Fix insert into collocation manifest

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/PostgresCollocationManifest.scala
Fix insert into the collocation manifest (take two).
When using .executeQuery() you must first call .next()
on the result before trying to get a value out.
> EN-17025: Fix insert into the collocation manifest

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/SoQLCommon.scala
Remove extra '.' from dataset internal name in data-coordinator's
collocation error responses.
> EN-21355: Remove extra '.' in collocation error

- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
Data-coordiantor should 400 on datasets with unrecognized instance
names given to the collocation API instead of 500.
> EN-21356: 400 on datasets w/unrecognized instances

- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
- project/Coordinator.scala
Initial unit test setup for CoordinatedCollocator
and unit tests for the following functions:
- Collocator.collocatedDatasets(.)
- Collocator.defaultStoresGroups
> EN-21688: Unit test for CoordinatedCollocator

- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Coordinator.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
Fix explain by comparing dataset instance name
to actual data-coordinator instance names.
Also add a couple basic unit test for explainCollocation
asserting fixed behavior. (See EN-21688)
> EN-21740: Fix collocation by fixing explain

- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
Fix "complex" collocations where datasets are already collocated
with other datasets.
> EN-21820: Fix "complex" collocations

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/CollocationSodaResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/SecondaryManifestsCollocateResource.scala
Take collocation job id as a passed parameter rather than generating it in data-coordinator. This allows core to more easily maintain a manifest of collocations.
> EN-21910: Pass JobId for Collocation

- configs/application.conf
- configs/sample.conf
Clearly comment that it was for solo (becaus I was confused).
Also, a little bit of config renaming to match spandex based
off of code reviews there.
> EN-22044: Explicit use of local.dev.socrata.net

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Coordinator.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Cost.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/secondary/stores/SecondaryStoreSelectorTest.scala
Add secondary-manifest/metrics endpoint to Coordinator service
to be used in explain and initiate of collocation by the Collocator
service.
Add the dataset size from the secondary-metrics API to Cost in
collocation, but don't do anything with it yet.
> EN-21686: Add secondary-metrics API to Coordinator

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
Delete entries from secondary_move_jobs when datasets are deleted
since secondary_move_jobs has a foreign key contraint to dataset_map.
> EN-21891: Delete entries from secondary_move_jobs

- coordinator-external/src/main/scala/com/socrata/datacoordinator/external/DataCoordinatorError.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/CollocationManifestsResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/SecondaryManifestsCollocateResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Router.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Service.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Coordinator.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/CollocationManifest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlCollocationManifest.scala
Drop entries from collocation manifests as datasets are deleted.
New route:
- `DELETE /collocation-manifest/{instance}/{dataset_system_id}`:
Drops entries for the given dataset from the collocation manifest
of the given data-coordinator instance.
> EN-22550: Drop entries from collocation manifests

- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
Add limits to collocation cost passed in the collocation
request such that data-coordinator can reject collocation
when the cost exceeds those limits.
Add a new `"limits"` field to the collocation request body
pointing to a Cost object.
Note: this is a breaking change! Since the new limits field
is required.
> EN-17026: Collocation API can reject collocation

- configs/sample.conf
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Metric.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/secondary/stores/SecondaryStoreSelector.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/MainTest.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/secondary/stores/SecondaryStoreSelectorTest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/config/SecondaryConfig.scala
Collocation API will not overfill secondary stores.
Reworks secondary store config to include values for the
store capacity. This capacity should be the rough capacity
the store has for row data and indices of datasets, it should
not include capacity needed to metadata.
> EN-17026: Collocation API will not overfill stores

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlCollocationManifest.scala
Because of the UNION ALL in the recursive query on the collocation
manifest causes the rows at each depth to increase factorially in
number (a problem for datasets with a large branching factor), the
query is far too slow -- and worse -- creates very large temp tables.
Replace the query with a breadth first search of the collocation
manifest implemented in scala.
> EN-24804: Fix collocation manifest recursive query

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/AdditionSecondary.scala
Include target column (in addition to source columns) in comparing row change/no change.
These two changes allow handlers to have more flexibility in determining when to recompute.
> EN-32060 Pass row and row previous image to handlers.

- coordinator-external/src/main/scala/com/socrata/datacoordinator/external/DataCoordinatorError.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/CoordinatorErrorsAndMetrics.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Mutator.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Service.scala
- coordinatorlib/src/it/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMapWriterTest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/SoQLCommon.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/DatasetInfo.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/DatasetMap.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/PostgresUniverse.scala
We already send back the new version on every mutation in a header, so
it is possible to do multiple writes while guaranteeing that no one
has touched the dataset in between.
This also presents the data version on exports, so it will be possible
to do an atomic read-modify-update cycle with dataset-level granularity.
This is all in support of doing incremental updates to datasets
externally.
> Allow gating updates by expected dataset version

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
What was there before was pretty bad, but the change to size-based
batching made it even worse.  Now we'll log the exact number of rows
per batch, because we have it and the other number isn't useful.
> Improve feedback logging

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/DocumentRep.scala
* Ensure all placeholders have `:: JSONB` casts
* Make `sql_in` and `sql_==` consistent
> Fix document SqlRep

- coordinatorlib/src/it/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMapWriterTest.scala
They're in it:test which isn't compiled unless you ask it to be.
> Fix a bunch of warnings I missed in the 2.12 upgrade

- build.sbt
It was to reduce the metaspace used, but we just increased the amount
we'll permit instead of making per-project changes.
Hopefully this PR builds!
> Undo classloader strategy

- coordinatorlib/src/main/java/com/socrata/datacoordinator/common/soql/sqlreps/FixedTimestampHelper.java
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/FixedTimestampRep.scala
This makes me sad, because we're now sending timestamps around as
strings, but java.sql.Timestamp doesn't deal with pre-Gregorian
dates very well.  But at least it ensures we'll read out the same
values we wrote in...
> Handle ancient timestamps better

- coordinatorlib/src/main/java/com/socrata/datacoordinator/common/soql/sqlreps/FixedTimestampHelper.java
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/FixedTimestampRep.scala
soql-postgres-adapter didn't like the previous one, where the select
list turned the timestamp into an ISO string.  Instead, we'll understand
Postgres's format.
> Get timestamps as strings, take 2

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/DataSourceFromConfig.scala
* it is now possible to get an unmanaged DsInfo
* the managed one is implemented in terms of the unmanaged one
* this is so that this logic doesn't need to be duplicated over in
pg-secondary
* which is currently is except for the tcp keep alive bit
> Refactor DataSourceFromConfig

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/AbstractRepBasedDataSqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlLoader.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/Sqlizer.scala
Before, deletes were scaled essentially by the size of the delete key.
They would be batched to a threshold and then sent to the worker
thread for processing.  However, the rows for that batch would then be
read out of the database (to populate the log with) and _that_ could
be large.  So now, when we're processing a batch of deletes, process
it in bounded-size chunks (specifically, the size that findRows will
naturally chunk in) to prevent this.
This isn't _completely_ ideal (in partciular, if a dataset has VERY
large rows we'll still end up with a large amount of memory in use
post-chunking) but that's a general problem when reading out of the
database as it's fundamentally row-chunk-based at the JDBC api level.
> Fix OOM when deleting a large number of rows out of a wide dataset

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
Before, we were finding the secondaries of dataset and then finding
any that were not (in our target collocation group and accepting new
datasets) but if the _DEFAULT_ meta-group has multiple groups in it,
then this will always fail when it asks "is this secondary from group B
in the set of datasets in group A that are still accepting datasets?"
So, when doing this check, limit ourselves to the secondaries that are
actually in the group under consideration.
> Fix ensuring dataset-in-same-secondaries when there's multiple colloc groups

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DebugResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Router.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Service.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/ServiceUtil.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/AbstractRepBasedDataSqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/PostgresRepBasedDataSqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlLoader.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/Sqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/StandardRepBasedDataSqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/util/DebugState.scala
This lets us poke an endpoint to say "hey, the next time this specific
thread starts doing a non-INSERT thing on the database as part of an
upsert operation, log the output of EXPLAINing that query".  INSERTs
are done via COPY which it doesn't really super make sense to EXPLAIN,
but DELETEs, UPDATEs, and the SELECTs to find existing rows all count.
> Allow ourselves to introspect query plans for specific upsert operations

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlDelogger.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/Universe.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/PostgresUniverse.scala
One of our persistent problems on the truthstores is related to long-running transactions preventing postgresql from vacuuming its transaction log.  In particular, there is a _lot_ of churn on secondary-manifest, both due to updates incrementing latest_data_version when they complete and the keepalive poking `claimed_at` every couple of minutes while a playback is in progress.
This prevents normal (non-resync) secondary playback from holding a transaction the entire time.  I'm hoping this will improve things because updates only touch secondary_manifest right at the very end of their transaction, whereas secondary playback touches it at the beginning _and_ the end, thus (my hypothesis goes) preventing secondary_manifest _in particular_ from being cleaned in a timely fashion.
> Do normal secondary playbacks without holding a truth transaction

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackCookie.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/CookieOperatorTest.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondaryTest.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/TestData.scala
- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
Replay requests are counted DCside and will mark the dataset broken over there automatically, so there's no need to count them on this side.
> Remove retry counts from secondarylib-feedback

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Mutator.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/DatabaseAccessors.scala
* never keep them
* previously preserved them until snapshotter could export a copy and store it in s3
* snapshotter functionality has been replaced by archival secondary service
> EN-56779: remove functionality around keeping snapshots

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
Not the start of the job
Before:
on every iteration of the loop we look to see if the _job_ starts
with consolidated versions, then (after the first iteration) we
discard them and just play back a single version.
Now:
on every iteration of the loop we look to see if the _remaining range_
of versions within the job is consolidatable, and if it is, consolidate
them
> EN-60867: scan for consolidatability from the current position

- Jenkinsfile
- coordinator/build.sbt
* The filename no longer contains the version number
* The file is stored in target instead of target/scala-$version
> Simplify assembly filename

- Jenkinsfile
- README.md
- For release builds, we check to see if there are changes (other than the version file) since the last release tag.  If so, we increase the patch version using `sbt release` and publish the changes using `sbt publish`.
- For release builds, the docker tag is in the socrata format (for example `data-coordinator:4.2.13_121_9f7a1a03`) and we push the image to all registries (even for a dry run).
- For main builds, the docker tag is in the socrata format (for example `data-coordinator:4.2.14-SNAPSHOT_115_888897f9`)
- For release builds, we use the RELEASE_NAME parameter (provided by the Release-Build job, which triggers data-coordinator-cut on release builds) for the release tag.  No publishing is done.
- For release builds, the docker tag is in the new format (for example …
> EN-61797: use release  name as git tag and deploy tag

- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcherConfig.scala
The Redshift secondary does not use typesafe config. It uses the quarkus config system.
This change allows us to construct a secondary watcher app without relying on a typesafe config.
> Allow creating secondary watcher app without needing a typesafe config

- Jenkinsfile
This commit moves the release tagging after a successful docker build. In order to do this, it separates the docker build from the publishing of the images into separate Jenkinsfile steps.
> EN-65714: move release tagging

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/DatasetMap.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
So that the PG secondary can preserve table modifiers across resyncs
> EN-67019: Allow unsafeCreateCopy'ing datasets with table modifiers

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/-impl/BaseDatasetMap.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
Certain operations the PG secondary was doing were using `allCopies`, which returns more than it's actually interested in.  The two new accessors are:
* `allActiveCopies` which returns only non-discarded copies
* `mostRecentlyChangedCopy` which returns the copy with the highest data version (not necessarily the copy with the highest copy number, e.g., if a working copy is created and discarded then a change happens to the published copy)
> Add a couple of accessors to the dataset-map

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
Otherwise our replication-delay logging will say "this retry was picked up (however long it's been since the dataset was previously updated)"
> When marking a dataset to be removed from a secondary, bump next_retry

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Mutator.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/TextRep.scala
Before, we were doing this on _inserts_ of specifically _text_ values. Now we do it everywhere a user-provided datum is a text value.
> EN-68076: Consistently remove NUL characters from text values

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/DatasetMap.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/sql/PostgresDatabaseMutator.scala
In order to hopefully avoid deadlocks based on different operations taking locks in different orders.
> EN-68632: Try eagerly locking secondary_manifest rows on mutations

- Jenkinsfile
After I merged https://github.com/socrata-platform/data-coordinator/pull/462, the main build failed because it tried to publish during the build phase.  This commit fixes the main build issue.
The release build job also failed during the Publish Library phase -- it should not be executing that phase so I've added a `when` condition to exclude it.
> EN-65991: fix publish build issue

- Jenkinsfile
- README.md
This commit updates the workflow for publishing the library.  After my previous PR, the snapshot version was published, which was not intended.  This commit fixes the issue so that the version tagged with the semver is checked out and published.
> EN-65991: checkout version tag before publishing

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryManifest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryReplicationMessages.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
- dataset-mover/src/main/scala/com/socrata/datacoordinator/mover/Main.scala
Before it would:
1. look up the dataset
2. find the latest copy
3. find _all_ copies (and throw away all but the published and unpublished)
4. look up the data versions in secondary_manifest
5. figure out which of those secondaries is a feedback secondary
6. figure out which of those secondaries is broken
7. look up the group name for each store
Now, 2 and 3 are combined into a single query, and 4-5-6-7 are all combined into one query.  This makes SecondaryManifest#stores slightly more expensive, but since it's only used in the secondaries-of-datasets function and the cross-truth-migrator, it should be a net win.
> Make secondaries-of-dataset do less databasing

- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlCollocationManifest.scala
Also add a bunch of type annotations for clarity, but the main thing is the addition of `toSet` in the datasetCostMap expression.
> EN-69380: Improve collocate's cost computation

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/IntervalRep.scala
This is only a quasi-type; you can't create columns of this type on a dataset (yet) but you _can_ create rollups with columns of this type and therefore it needs a sql rep.  It's not actually used here, only over in soql-postgres-adapter
> Add a SqlRep for SoQLInterval

- coordinatorlib/src/main/java/com/socrata/datacoordinator/truth/loader/snappy/SlowMemory.java
- coordinatorlib/src/main/java/com/socrata/datacoordinator/truth/loader/snappy/SnappyInternalUtils.java
Not bothering to port over UnsafeMemory; I trust in HotSpot
> Ensure the `Memory` implementation actually exists

- Jenkinsfile
While working on migrating from marathon to ECS, we are keeping the tagged images up to date. This commit adds the mechanism for the ECS deployment in addition to the marathon deployment. Once the migration is done, we will remove the marathonDeploy and leave in place the ECS deployment.
> EN-76223: deploy to ECS as well as marathon

- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20250410-create-purge_copy_map-function-trigger.xml
Hot fix to resolve bug that occurs when trying to update a dataset with indices. This has been fixed in Staging via #490 and was introduced in #487.
(cherry picked from commit 9149fa15b473d4dfee12927e543c2a591c38d46d)
> HF-43 - Fix copy_map purge (#490)
