socrata-platform/data-coordinator

- coordinatorlib-soql/src/main/scala/com/socrata/datacoordinator/common/soql/jsonreps/GeometryLikeRep.scala
- coordinatorlib-soql/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/GeometryLikeRep.scala
- project/Dependencies.scala
Basically the same change as for soda-fountain.  The types are also used in PG server.
DO NOT MERGE YET... need to bump soql-reference to a published version.
> Read geometries as WKB; read and write CJSON using WKB64

- coordinatorlib-soql/src/main/scala/com/socrata/datacoordinator/common/soql/SoQLRep.scala
- coordinatorlib-soql/src/main/scala/com/socrata/datacoordinator/common/soql/SoQLRowLogCodec.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/migration/Migration.scala
- project/Dependencies.scala
* added new types to SoqlRep and RowLogCodecs
* change migrate loglevel to supress some spam
* todo: update dependencies file and remove snapshot ref
> Refs CORE-5412

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Mutator.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Service.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/DatabaseAccessors.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/sql/PostgresDatabaseMutator.scala
Don't advance dataVersion on published copy when working copy is dropped.
> Dont upd dataversion

- coordinator/src/main/resources/reference.conf
- coordinator/src/main/scala/com/socrata/datacoordinator/common/SoQLCommon.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/ServiceConfig.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/PostgresUniverse.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/SqlTableCleanup.scala
- added default value to reference.conf
- modified Tablecleanup function to accept a finiteduration type.
- Modified calls to SoQLCommon to include a tableCleanupDelay parameter.
> Ability to delay the deletion of a table by x days:

- .gitignore
- coordinator/docker/data-coordinator.conf.j2
- coordinator/src/main/resources/reference.conf
- coordinator/src/main/scala/com/socrata/datacoordinator/common/SoQLCommon.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Service.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/ServiceConfig.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/secondary/SecondaryWatcherTest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/PostgresUniverse.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/SqlTableCleanup.scala
- project/Coordinator.scala
Also commented out Nathalie's changes.
> increase jetty idle timeout to 5 minutes from 30 seconds

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
is the parameter inside single quotes not allowed?
> set interval as string param

- coordinator/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Service.scala
- project/BuildSettings.scala
Log version when starting secondary-watcher.
> Specify build info package name.

- coordinator/src/main/resources/reference.conf
* Raise the command-read-limit to 70m to match soda-fountain
and not die on shapefile imports
> Refs CORE-7133

- coordinator-external/src/main/scala/com/socrata/datacoordinator/external/DataCoordinatorError.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/common/util/DatasetIdNormalizer.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetRollupResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetSchemaResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetSecondaryStatusResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/ErrorHandlingSodaResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/NotFoundDatasetResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/SecondariesOfDatasetResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/SecondaryManifestsResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/SodaResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/VersionResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/CoordinatorErrorsAndMetrics.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Mutator.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Router.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Service.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/ServiceUtil.scala
- project/CoordinatorExternal.scala
- project/DataCoordinator.scala
first major part of refactoring DC. Should be all we need to do for the most part, but could hold out for more suggestions.
removed uncessary dep.
Updated a few error messages that I have missed in a few resource files. Created a new error for bad request due to content type errors.
adding fix to resource type and expected in router class.
adding fix to resource type and expected in router class: extended to main and service class also.
removed extra space
> Soda Error Handling and Refactoring. 

- coordinatorlib-soql/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/LocationRep.scala
This is a fall out from the task.  upserting null location value fails because a wrong sub-column index was used.
> BUG: EN-1135 location type bug.

- coordinatorlib-soql/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/TextRep.scala
* Remove nul char from text reps, as it breaks postgres
* integration tests sold separately
> Refs EN-1589

- coordinator/docker/data-coordinator.conf.j2
> Refs EN-1737

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetResource.scala
- Adds missing implicit parameter
> Fixes issues EN-1945

- coordinatorlib-soql/src/main/scala/com/socrata/datacoordinator/common/soql/SoQLRep.scala
This is causing problem in combination of chained soql and rollup.
> EN-1783 Make money rep represent money type.

- project/SecondaryLibFeedback.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/instance/FeedbackSecondaryInstance.scala
Actually use data-coordinator instance name
> EN-158: Fix feedback secondary service discovery

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
Report the correct number of row updates
> EN-158: Fix logging in feedback secondary

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/PostgresUniverse.scala
Reset the transaction isolation level after commit
and rollback to default level READ COMMITTED.
> EN-4304: Reset transaction isolation level

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
- dummy-secondary/src/main/scala/com/socrata/dummysecondary/DummySecondary.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/Secondary.scala
- version.sbt
Reverts socrata-platform/data-coordinator#100
> Revert "EN-4323/hotfix"

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetSecondaryStatusResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/secondary/SecondaryWatcherTest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryManifest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
- dummy-secondary/src/main/scala/com/socrata/dummysecondary/DummySecondary.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/Secondary.scala
Remaining changes for EN-4323 to by merged to master.
> EN-4323 remaining changes

- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20160422-drop-latest-secondary-lifecycle-stage-column.xml
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/migrate.xml
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
> Drop unused column from `secondary manifest`

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
> More order by `data_version` and not `copy_number`

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlDatasetDropper.scala
Actually remove all references to `latest_secondary_lifecycle_stage`
> Fix deleting datasets

- coordinator/docker/Dockerfile
So far so good building and running in staging. Will merge when it's sat there peacefully for a bit.
> EN-5906: Use java8 base image for data-coordinator

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackCookie.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/instance/FeedbackSecondaryInstance.scala
- secondarylib/src/main/scala/com/socrata/datacoordinator/id/ColumnId.scala
- secondarylib/src/main/scala/com/socrata/datacoordinator/id/UserColumnId.scala
A few things could use more refactoring (specifically, user and retry-count shouldn't be `ComputationHandler`-specific) but mostly I'm happy with this setup.
> Preparations for multi-ComputationHandler feedback secondaries

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
Actually throw resync exception when a computed
column of the matching strategies is added.
Removes using current cookie as previous after
resync... I don't think it is correct to do so.
> EN-7507: Throw resync exc when comp col is addd

- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
We have them in the config file after all.
> Don't require that instance-names be passed in at all.

- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/triggers/update-dataset-log-trigger.xml
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlDatasetDropper.scala
- project/Coordinator.scala
This has caused a deadlock at least once, and it isn't used anywhere anymore.  Most of the code that deals with it has long since been removed.  It's just a stray leftover.
> Remove some leftover userspace-backup code

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/SoQLCommon.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/DatabaseAccessors.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/Universe.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/PostgresUniverse.scala
- project/CoordinatorLib.scala
validate and drop invalid rollups on publish
> delete invalid rollup on publish

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/SqlLogTableCleanup.scala
Even when explain plan shows that more than one rows are locked w/o this patch, it doesn’t seem to actually lock the other rows (at least the 2nd row from the ordered list).
This changes explicitly make explain plan to show lockrows = 1 at the cost of slower query (at ms scale)
From
LockRows  (cost=0.41..139413.49 rows=118818 width=22)
to
LockRows  (cost=2.01..10.06 rows=1 width=46)
> EN-13228 May be this will reduce the number of rows locked?

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
We want to commit before updating the `latest_secondary_data_version`
to end the current transaction during replay to try to avoid deadlocks
when data-coordinator is also updating the `latest_data_version` for
the same row and is writing to the log tables that the secondary-watcher
was also trying to read from.
Deadlocks at the end of replay cause the secondary-watcher to go into
a resync which causes the dataset to not be available for read.
> EN-13225:Commit before updating secondary-manifest

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
> Fix "list snapshots" query

- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
Remove the job from our in memory list first, and then unclaim it in the database.
> EN-16021: Prevent race condition in "already claimed" assertion.

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
In the Feedback Secondary don't track CreatedColumnEvents
after WorkingCopyEvents as new computed columns and thus
recompute computed columns whenever working copies are created.
> EN-17249: Don't recompute columns on WC creation

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/DatasetSnapshotResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
..so be sure to take the appropriate row lock in truth when dropping
them.
> Deleting snapshots is a write operation

- project/Dependencies.scala
That actually contains the fix for this bug.
> EN-18388: Update soql-reference

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/AbstractRepBasedDataSqlizer.scala
By making sure that PG keeps the column stats for the PK column up to
date.
> EN-17812: Improve big inserts with row identifiers

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
This reverts commit 643cba1812b413184f4b5c29c84f3e1ea2045c90.
> Revert "EN-18250: Hack secondaries-of-dataset endpoint (#186)"

- coordinator-external/src/main/scala/com/socrata/datacoordinator/external/DataCoordinatorError.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/CollocationManifestsResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/CollocationSodaResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/SecondaryManifestsCollocateResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/SecondaryManifestsMoveResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Coordinator.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/graph/GraphTest.scala
- coordinatorlib/src/main/resources/reference.conf
- TODOs for better error responses for malformed requests
in the collocation Resources
- TODOs in Main, GraphTest, and reference.conf
- TODOS around error handling and assertions in Collocator
and Coordinator
- Leave TODO for better "Cost" for later work
> EN-210503: Address TODOs in initial collocation work

- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
Positive unit tests for CoordinatedCollocator.explainCollocation(.)
> EN-21831: Positive tests for explainCollocation

- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
Unit tests for CoordinatedCollocator covering the follwing functions:
- saveCollocation(.)
- beginCollocation()
- commitCollocation()
- rollbackCollocation()
> EN-21831: More tests for CoordinatedCollocator

- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
Positive unit tests for CoordinatedCollocator.initiateCollocation(.)
> EN-21831: Positive tests for initiateCollocation

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/SecondaryManifestsCollocateResource.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/collocation/CollocationManifest.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/collocation/TestData.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/resources/collocation/SecondaryManifestsCollocateResourceTest.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
Unit tests for the primary collocation resource
SecondaryManifestsCollocateResource.
> EN-21831: Unit tests for Collocation Resource

- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Coordinator.scala
So data-coordinator does not 400 on collocation.
> EN-22803: Fix stupid bug with extra "/" in path

- .gitignore
- .solo/data-coordinator-alpha.json
- .solo/data-coordinator-bravo.json
- .solo/data-coordinator-charlie.json
- bin/run_migrations.sh
- bin/start_dc.sh
- bin/start_dc_alpha.sh
- bin/start_dc_bravo.sh
- bin/start_dc_charlie.sh
- bin/start_dc_docker_alpha.sh
- bin/start_dc_docker_bravo.sh
- bin/start_dc_docker_charlie.sh
- configs/sample.conf
Add solo config and start scripts to run the phonetic
truth cluster "alpha", "bravo", and "charlie" for
local development with multiple truth shards.
> Add solo configuration for phonetic dc cluster

- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
- secondarylib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryWatcher.scala
> EN-27593 Speed up collocation calculation call

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
This will be consumed in the geocoding secondary project.
> EN-27911 Update computation strategy in secondary_manifest.cookie

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/FixedTimestampRep.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/GeometryLikeRep.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/AbstractRepBasedDataSqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/PostgresRepBasedDataSqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlLoader.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlPrevettedLoader.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/Sqlizer.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/StandardRepBasedDataSqlizer.scala
- coordinatorlib/src/test/scala/com/socrata/datacoordinator/truth/loader/sql/StupidSqlLoader.scala
While it's not comparable to the improvement COPY gives you over INSERT,
this is somewhat faster than batched single updates.
> Use bulk update statements with pgsql, not just batched single updates

- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/DataCoordinatorClient.scala
We just tracked down a problem where the geocoding secondary was
causing a mysterious "malformed json" 500 from data-coordinator.  This
is what was happening:
* The feedback secondary sends its mutation script to DC.  This
involves using a JsonEventIterator to create the POST body.
* DC was 500ing because of an unrelated bug (see parent commit)
* The feedback secondary retried, but using the partially-consumed
event iterator, so the mutator started reading in the middle
of a JSON datum and went "bwuh!??!"
This fix makes the retry logic recreate the event iterator when
the retry occurs.
> Fix feedback retry

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlLoader.scala
- coordinatorlib/src/test/scala/com/socrata/datacoordinator/truth/loader/sql/TestSqlLoader.scala
This would 500.  Now it just returns "no such row to delete", which I
think is reasonable.
> EN-37185: Fix deleting rows with a `null` value

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/SecondariesOfDatasetResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
- coordinator/src/test/scala/com/socrata/datacoordinator/service/collocation/CoordinatedCollocatorTest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryManifest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/CopyInfo.scala
* also convert CopyInfo to use shared library for joda DateTime json codec
> brokenSecondaries to secondaries-of-dataset endpoint

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Mutator.scala
- coordinatorlib/src/it/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMapWriterIndexDirectivesTest.scala
- coordinatorlib/src/it/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMapWriterTest.scala
- coordinatorlib/src/main/protobuf/LogData.proto
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20200901-create-index-directives.xml
- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/migrate.xml
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/Event.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/Secondary.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/DatabaseAccessors.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/Delogger.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/Logger.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/NullLogger.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/AbstractSqlLogger.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlDelogger.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlLogger.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/-impl/BaseDatasetMap.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/IndexDirectives.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/IndexControl.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
- dummy-secondary/src/main/scala/com/socrata/dummysecondary/DummySecondary.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondary.scala
- secondarylib-feedback/src/test/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackSecondaryTest.scala
Add index_directives table in migration
> EN-40823: add secondary instruction - delete index

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/PlaybackToSecondary.scala
Turns out this is important when you have large datasets being delta-
updated regularly!
> Allow empty upserts to be consolidated.

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/SecondaryManifestsCollocateResource.scala
> Don't _just_ internal-error when collocation fails unexpectedly.

- coordinator/src/main/scala/com/socrata/datacoordinator/service/collocation/Collocator.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/id/DatasetInternalName.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/SecondaryMetrics.scala
Why does it want to move a dataset from a store which it is not in?
> Add a bunch of collocation logging

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
And in particular, don't fail with "I couldn't find that dataset in
the specified store"!
> Don't fail moving a dataset when it's already in the desired store

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/SoQLRep.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/csvreps/JsonRep.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/jsonreps/JsonRep.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/sqlreps/JsonRep.scala
- project/Dependencies.scala
* initial support for soql json data type
* depends on https://github.com/socrata-platform/soql-reference/pull/183
* to be merged after https://github.com/socrata-platform/soql-postgres-adapter/pull/393
> EN-45573 SoQLJson support

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/util/TimingReport.scala
Be able to debug and info with the same timing report
> Make timing report a little more flexible

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/RollupInfo.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/metadata/sql/PostgresDatasetMap.scala
Make rollup_map.raw_soql survive publication cycle
> EN-52670: Add column rollup_map.raw_soql, more

- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/SecondaryManifestsMoveResource.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/DataCoordinatorClient.scala
- secondarylib-feedback/src/main/scala/com/socrata/datacoordinator/secondary/feedback/FeedbackContext.scala
I'm pretty sure these were all bugs that just happened to go unnoticed
since they're all exceptions.
> Import the v3 instead of the v2 versions of various rojoma-json things

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/common/soql/jsonreps/JsonRep.scala
- coordinatorlib/src/test/scala/com/socrata/datacoordinator/common/soql/jsonreps/SoQLJsonRepTest.scala
* if you upserted a null value in a soql json
column, it would crash
> Fix crash when on null SoQLJson cells

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/sql/SqlSecondaryManifest.scala
This appears to have exactly the behavior we want with respect to
number of rows locked by the query.
> Use SKIP LOCKED for postgresql dequeue instead of a subselect

- coordinator/src/main/scala/com/socrata/datacoordinator/service/Mutator.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/DatabaseAccessors.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/Truncator.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/loader/sql/SqlTruncator.scala
Also include the time to do the truncation.
> Include truncated data in the logged "rows deleted" line

- .run/data-coordinator.run.xml
- project/Dependencies.scala
Just need to propagate the soql-reference changes here, as we did with query-coordinator
> EN-58705: soql-reference version bump for column mapping fix

- Jenkinsfile
In the Jenkinsfile, on release cuts, the dockerized image deployed to RC.
In the Jenkinsfile, on release builds, the dockerized image is not deployed to RC.
Also:
- new parameter RELEASE_DRY_RUN added to ease testing
- changed stage name from "Cut" to "Release Tag"
- used simpler syntax for deploying
- simplified logic for which stage to build
> EN-59949: update Jenkinsfile

- README.md
- configs/sample.conf
- coordinator/src/main/scala/com/socrata/datacoordinator/service/Main.scala
As described on the tin, this removes some config and mentions.  I almost won't did this ticket, b/c these are such small, non-important changes.  But eh - I like being thorough. 
😬 I compiled it.
> EN-64511: remove spandex config and mentions

- configs/sample.conf
Before:
- No Redshift configs in sample
After:
- Redshift configs
> add sample redshift configs

- coordinator-external/src/main/scala/com/socrata/datacoordinator/external/DataCoordinatorError.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/CollocationSodaResource.scala
- coordinator/src/main/scala/com/socrata/datacoordinator/resources/collocation/SecondaryManifestsCollocateResource.scala
So that soda-fountain can propagate it properly.
> EN-67321: Build a proper error response for collocate lock timeout

- project/Dependencies.scala
- version.sbt
Quite a few CVEs related to this one, most urgently:
[EN-69707](https://socrata.atlassian.net/browse/EN-69707) : CVE-2016-3088 : critical
[EN-69707]: https://socrata.atlassian.net/browse/EN-69707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Aqua scan fix for amq client

- project/Dependencies.scala
Updating the library versions from the scans
> bump library versions

- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/SqlLogTableCleanup.scala
- coordinatorlib/src/main/scala/com/socrata/datacoordinator/truth/universe/sql/SqlTableCleanup.scala
Lets us work on other things if one instance is taking its time doing cleanups
> For some cleanup operations, do SKIP LOCKED when claiming the work

- coordinatorlib/src/main/java/com/socrata/datacoordinator/truth/loader/snappy/SnappyInputStream.java
This is preventing publishing the coordinator jar
> Work around a scaladoc bug

- coordinator/docker/Dockerfile
- coordinator/docker/data-coordinator.conf.j2
- coordinator/docker/ship.d/run
* get public IP out of the metadata service
* get truth pwd out of an env var if set
> ECS preparation

- coordinatorlib/src/main/resources/com.socrata.datacoordinator.truth.schema/20250410-create-purge_copy_map-function-trigger.xml
> Fix copy_map purge

- Jenkinsfile
This commit tests out and the implements the new methods to automatically create and clean up hotfix branches as part of the initial release build.
> EN-78944: create and cleanup hotfix branches
